import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Home from "./page";
import { Bounded } from "../components/Bounded";

const alpino = localFont({
  src: "../../public/fonts/Alpino-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-alpino",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={alpino.variable}>
      <body className="bg-yellow-300 overflow-x-hidden">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
